name = "schrimpf"
uuid = "0c925310-898a-4353-9daa-a5e3838dd3b4"
repo = "https://github.com/schrimpf/julia-registry.git"
description = "Registry for packages under development"

[packages]
d602b1ce-c8e8-436d-8dfe-952725c75295 = { name = "CovidData", path = "C/CovidData" }
e19e442c-8718-4e02-b74e-289a16846d3b = { name = "CovidRt", path = "C/CovidRt" }
